# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "打包出来"	
  lane :doIpa do 
    scheme_name = "TestDemo1" 
    output_directory = "/Users/caohouhong/Desktop/IPA_Info"
    #导出名称 
    output_name = "#{scheme_name}_#{Time.now.strftime('%Y%m%d%H%M%S')}.ipa"
    gym(
      export_method: "ad-hoc", #这里填写导出方式 ad-hoc、enterprise、app-store
      export_xcargs: "-allowProvisioningUpdates", 
      scheme: scheme_name,# target的名字
      clean: true, # 在构建前先clean
      output_directory: output_directory + "/pgy",
      output_name: output_name,
  ) 
  end
 

  desc "上传蒲公英测试"	
  lane :beta do 
    scheme_name = "TestDemo1" 
    output_directory = "/Users/xxx/Desktop/IPA_Info"
    #导出名称 
    output_name = "#{scheme_name}_#{Time.now.strftime('%Y%m%d%H%M%S')}.ipa"
    gym(
      export_method: "ad-hoc", #这里填写导出方式 ad-hoc、enterprise、app-store
      export_xcargs: "-allowProvisioningUpdates", 
      scheme: scheme_name,# target的名字
      clean: true, # 在构建前先clean
      output_directory: output_directory,
      output_name: output_name,
  ) 
    pgyer(api_key: "e48afa62xxxxx3db4136227b2f3ba4", user_key: "5e50ae3a91a8011xxxxxc62f1baa5f") 
  end
  
  desc "上传新版本到 App Store"
  lane :release do
    # 增加build版本号
    increment_build_number
    scheme_name = "TestDemo1" 
    output_directory = "/Users/xxx/Desktop/IPA_Info"
    #导出名称 
    output_name = "#{scheme_name}_#{Time.now.strftime('%Y%m%d%H%M%S')}.ipa"
    gym(
      export_method: "app-store", #这里填写导出方式 ad-hoc、enterprise、app-store 
      export_xcargs: "-allowProvisioningUpdates", 
      scheme: scheme_name,# target的名字
      clean: true, # 在构建前先clean
      output_directory: output_directory,
      output_name: output_name,
    ) 
    deliver
  end
end
